# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('host_name', models.CharField(max_length=50)),
                ('host_purpose', models.CharField(blank=True, max_length=100)),
                ('admin_Account', models.CharField(default='', max_length=50)),
                ('admin_password', models.CharField(default='', max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostCategorys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='HostGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='Host_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.HostCategorys'),
        ),
        migrations.AddField(
            model_name='host',
            name='Host_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.HostGroups'),
        ),
    ]
