# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 04:57
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP地址')),
                ('host_name', models.CharField(max_length=50)),
                ('host_purpose', models.CharField(blank=True, max_length=100)),
                ('admin_Account', models.CharField(blank=True, max_length=50)),
                ('admin_password', models.CharField(blank=True, max_length=50)),
                ('Host_body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='正文')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HostCategorys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='HostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostcomments', to='app.Host')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='HostGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='OperatingSystems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='Host_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.HostCategorys'),
        ),
        migrations.AddField(
            model_name='host',
            name='Host_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.HostGroups'),
        ),
        migrations.AddField(
            model_name='host',
            name='Host_operatingsystem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.OperatingSystems'),
        ),
        migrations.AddField(
            model_name='host',
            name='host_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Host_status'),
        ),
    ]
