# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostcomment',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='hostcomment',
            name='author',
            field=models.CharField(default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='hostcomment',
            name='body',
            field=models.CharField(max_length=100, verbose_name='操作记录'),
        ),
    ]
