# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170911_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host_status',
            old_name='status',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='hostgroups',
            old_name='group',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='operatingsystems',
            old_name='operatingsystem',
            new_name='name',
        ),
    ]
