# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170911_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostcategorys',
            old_name='category',
            new_name='name',
        ),
    ]
