# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170911_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
